env:
  _JAVA_OPTIONS="-Xms1G -Xmx4G"

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - doxygen
      - oracle-java8-installer

install: true

script:
  - mvn -Dmaven.javadoc.skip=true -DskipTests=true clean verify

notifications:
  irc: "chat.freenode.net#io7m"

